FROM alpine:latest as alpine-base

#DEPENDENCIAS PARA O HOPE
RUN apk update
RUN apk add --no-cache make
RUN apk add --no-cache git
RUN apk add --no-cache build-base
RUN apk add --no-cache bison
# RUN apk add --no-cache gcc
# RUN apk add --no-cache g++
# RUN apk add --no-cache gawk
# RUN apk add --no-cache mawk
# RUN apk add --no-cache flex
# RUN apk add --no-cache bash
# RUN apk add --no-cache byacc
# RUN apk add --no-cache libc-dev
# RUN apk add --no-cache libffi-dev


#CLONA O REPOSITORIO DO HOPE
RUN git clone https://github.com/dmbaturin/hope.git

#ACESSA E INSTALA O HOPE
WORKDIR /hope
RUN make install

#CRIAR DIRETORIO PARA O HOPE
WORKDIR /hope/HOME

# CMD [ "hope" ]
